spring.application.name=jobhunter
spring.datasource.url=jdbc:postgresql://localhost:5432/jobhunter
spring.datasource.username=jobhunter
spring.datasource.password=${POSTGRES_PASSWORD}

# CONFIGURACION PARA HIBERNATE
spring.jpa.hibernate.ddl-auto=update